feature: Unify Thank you pages in a reusable component
Light-it-labs/eo_web pull request #140
Opened 2024-05-07 15:27 UTC by LeoBLightIt

# Refactor Thank You pages ⚡⚡⚡

_Resolve_: [closes -86dt88j0r](https://app.clickup.com/t/86dt88j0r)

## Description and Requires ⭐

Refactor code for thank you pages unifying in a single Thank You component

## Checklist ✅

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-05-07 17:22 UTC, hyanez-lightit requested changes
Small suggestion

2024-05-07 17:22 UTC, hyanez-lightit commented on apps/eo_web/src/components/ThankYou.tsx
> +  }
Another approach to early exit & navigate

```suggestion
  if (!submission_id) {
    return <Navigate to={exitRoute} />
  }
```

2024-05-07 17:22 UTC, hyanez-lightit commented on apps/eo_web/src/components/ThankYou.tsx
> +        </>}
Fragment is unnecessary

2024-05-08 12:19 UTC, LeoBLightIt commented on apps/eo_web/src/components/ThankYou.tsx
> +              Thank you!
I'm using that as a default because it's shared by 2 out of the 3 pages

2024-05-08 15:13 UTC, sgoycoechea-lightit commented on apps/eo_web/src/components/ThankYou.tsx
> +  const submission_id = searchParams.get("submission_id") ?? "";
I think all the `submission_id` related stuff should be in the parent components, it shouldn't be a responsibility of the `ThankYou` component.

We should pass it in the `mutationKey` and `mutationParams`, and move the navigate to the parent as well.

2024-05-09 12:40 UTC, sgoycoechea-lightit approved these changes

2024-05-09 12:44 UTC, merged